---
- hosts: servidor_mysql
  sudo: yes
  vars:
    mysql_root_db_pass: 'asdasd'
  tasks:
    - name: install mysql
      apt: name={{ item }} state=latest
      with_items:
        - mysql-server
        - python-mysqldb 

    - name: Ensure mysql binds to internal interface
      template: >
        src=templates/my.cnf 
        dest=/etc/mysql/my.cnf 
        owner=root 
        group=root 
        mode=0644
      notify: restart mysql
    
    - name: update mysql root password for locahost accounts
      mysql_user: >
        name=root
        host=localhost
        password={{ mysql_root_db_pass }}
    - name: copy .my.cnf file with root password credentials
      template: src=templates/.my.cnf.j2 dest=~/.my.cnf owner=root mode=0600


    - name: update mysql root password for all root accounts
      mysql_user: name=root host={{ item }} password={{ mysql_root_db_pass }}
      with_items:
        - "{{ ansible_hostname }}"
        - localhost


  handlers:
    - name: restart mysql
      service: name=mysql state=restarted